import { z } from 'zod';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { ToolContext } from '../core/context.js';
import { assertToolPermitted } from '../core/policy.js';
import { which } from '../core/platform.js';
const exec=promisify(execFile);
export function registerDatabaseTools(server:McpServer,ctx:ToolContext):void{
 server.registerTool('database_query',{description:'Run a database query using an installed mysql, psql, or redis-cli client. Credentials are read from a named environment variable and never returned.',inputSchema:{engine:z.enum(['mysql','postgres','redis']),query:z.string(),credential_env:z.string().regex(/^[A-Z_][A-Z0-9_]*$/)}},async({engine,query,credential_env})=>{assertToolPermitted({tool:'database_query',scopes:ctx.token.scopes,readOnly:ctx.readOnly});const bin=engine==='postgres'?'psql':engine==='mysql'?'mysql':'redis-cli';if(!which(bin))return{content:[{type:'text',text:`${bin} is not installed.`}],isError:true};const secret=process.env[credential_env];if(!secret)return{content:[{type:'text',text:`Credential environment variable ${credential_env} is not set.`}],isError:true};try{const args=engine==='redis'?['-u',secret,'--no-auth-warning',query]:engine==='postgres'?['--csv',query]:['--batch','--raw','-e',query];const r=await exec(bin,args,{env:{...process.env,MYSQL_PWD:engine==='mysql'?secret:process.env.MYSQL_PWD,PGPASSWORD:engine==='postgres'?secret:process.env.PGPASSWORD},timeout:120000,maxBuffer:2*1024*1024});return{content:[{type:'text',text:(r.stdout||r.stderr).slice(0,200000)}]};}catch(e:any){return{content:[{type:'text',text:(e.stdout||e.stderr||e.message).slice(0,200000)}],isError:true};}});
 server.registerTool('database_schema',{description:'Inspect database schema using an installed mysql or psql client. Credentials stay in an environment variable.',inputSchema:{engine:z.enum(['mysql','postgres']),credential_env:z.string().regex(/^[A-Z_][A-Z0-9_]*$/)}},async({engine,credential_env})=>{assertToolPermitted({tool:'database_schema',scopes:ctx.token.scopes,readOnly:ctx.readOnly});const bin=engine==='postgres'?'psql':'mysql';if(!which(bin))return{content:[{type:'text',text:`${bin} is not installed.`}],isError:true};const secret=process.env[credential_env];if(!secret)return{content:[{type:'text',text:`Credential environment variable ${credential_env} is not set.`}],isError:true};const query=engine==='mysql'?'SHOW DATABASES;':'SELECT table_schema, table_name FROM information_schema.tables WHERE table_schema NOT IN (\'pg_catalog\',\'information_schema\');';try{const args=engine==='postgres'?['--csv','-c',query]:['--batch','--raw','-e',query];const r=await exec(bin,args,{env:{...process.env,MYSQL_PWD:engine==='mysql'?secret:process.env.MYSQL_PWD,PGPASSWORD:engine==='postgres'?secret:process.env.PGPASSWORD},timeout:120000,maxBuffer:2*1024*1024});return{content:[{type:'text',text:(r.stdout||r.stderr).slice(0,200000)}]};}catch(e:any){return{content:[{type:'text',text:(e.stdout||e.stderr||e.message).slice(0,200000)}],isError:true};}});
}
